spring:
  jackson:
    time-zone: America/Bogota
  application:
    name: shopping-cart
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    com:
      indra: DEBUG